apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-app-frontend
  namespace: medical-app-frontend
  labels:
    app: medical-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medical-app-frontend
  template:
    metadata:
      labels:
        app: medical-app-frontend
    spec:
      containers:
      - name: medical-app-frontend
        image: your-ecr-repo/medical-app:latest
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: NODE_ENV
        - name: SUPABASE_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: SUPABASE_URL
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: SUPABASE_ANON_KEY
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
