# Optional: Monitoring setup with Prometheus and Grafana
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
# ServiceMonitor for the medical app
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: medical-app-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: medical-app-frontend
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
---
# Basic AlertManager rules
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: medical-app-rules
  namespace: monitoring
spec:
  groups:
  - name: medical-app
    rules:
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High error rate detected
    - alert: HighLatency
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High latency detected